# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")

        # left column
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")

####################################################################################
# graph area
####################################################################################
        self.graph_Widget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_Widget.sizePolicy().hasHeightForWidth())
        self.graph_Widget.setSizePolicy(sizePolicy)
        self.graph_Widget.setMinimumSize(QtCore.QSize(640, 480))
        self.graph_Widget.setMaximumSize(QtCore.QSize(999999, 999999))
        self.graph_Widget.setAutoFillBackground(True)
        self.graph_Widget.setObjectName("graph_Widget")
        self.verticalLayout_7.addWidget(self.graph_Widget)


####################################################################################
# left-lower area where we set mode
####################################################################################
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 230))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cursors_Tabber = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cursors_Tabber.sizePolicy().hasHeightForWidth())
        self.cursors_Tabber.setSizePolicy(sizePolicy)
        self.cursors_Tabber.setMinimumSize(QtCore.QSize(900, 210))
        self.cursors_Tabber.setMaximumSize(QtCore.QSize(900, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cursors_Tabber.setFont(font)
        self.cursors_Tabber.setTabPosition(QtWidgets.QTabWidget.North)
        self.cursors_Tabber.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.cursors_Tabber.setObjectName("cursors_Tabber")


####################################################################################
# left-lower area tab1 : deltas
####################################################################################
        self.tab_Deltas = QtWidgets.QWidget()
        self.tab_Deltas.setObjectName("tab_Deltas")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Deltas)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.current_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_Y.sizePolicy().hasHeightForWidth())
        self.current_Y.setSizePolicy(sizePolicy)
        self.current_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.current_Y.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_Y.setFont(font)
        self.current_Y.setObjectName("current_Y")
        self.gridLayout_3.addWidget(self.current_Y, 4, 1, 1, 1)

        self.deltas_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltas_Label.sizePolicy().hasHeightForWidth())
        self.deltas_Label.setSizePolicy(sizePolicy)
        self.deltas_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.deltas_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.deltas_Label.setObjectName("deltas_Label")
        self.gridLayout_3.addWidget(self.deltas_Label, 2, 4, 1, 1)

        self.click_1_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_1_X.sizePolicy().hasHeightForWidth())
        self.click_1_X.setSizePolicy(sizePolicy)
        self.click_1_X.setMinimumSize(QtCore.QSize(120, 20))
        self.click_1_X.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.click_1_X.setFont(font)
        self.click_1_X.setObjectName("click_1_X")
        self.gridLayout_3.addWidget(self.click_1_X, 3, 2, 1, 1)

        self.current_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_Label.sizePolicy().hasHeightForWidth())
        self.current_Label.setSizePolicy(sizePolicy)
        self.current_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.current_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.current_Label.setObjectName("current_Label")
        self.gridLayout_3.addWidget(self.current_Label, 2, 1, 1, 1)

        self.click_2_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_2_Y.sizePolicy().hasHeightForWidth())
        self.click_2_Y.setSizePolicy(sizePolicy)
        self.click_2_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.click_2_Y.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.click_2_Y.setFont(font)
        self.click_2_Y.setObjectName("click_2_Y")
        self.gridLayout_3.addWidget(self.click_2_Y, 4, 3, 1, 1)

        self.delta_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delta_Y.sizePolicy().hasHeightForWidth())
        self.delta_Y.setSizePolicy(sizePolicy)
        self.delta_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.delta_Y.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_Y.setFont(font)
        self.delta_Y.setObjectName("delta_Y")
        self.gridLayout_3.addWidget(self.delta_Y, 4, 4, 1, 1)

        self.click1_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click1_Label.sizePolicy().hasHeightForWidth())
        self.click1_Label.setSizePolicy(sizePolicy)
        self.click1_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.click1_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.click1_Label.setObjectName("click1_Label")
        self.gridLayout_3.addWidget(self.click1_Label, 2, 2, 1, 1)

        self.delta_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delta_X.sizePolicy().hasHeightForWidth())
        self.delta_X.setSizePolicy(sizePolicy)
        self.delta_X.setMinimumSize(QtCore.QSize(120, 20))
        self.delta_X.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delta_X.setFont(font)
        self.delta_X.setObjectName("delta_X")
        self.gridLayout_3.addWidget(self.delta_X, 3, 4, 1, 1)

        self.y_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_Label.sizePolicy().hasHeightForWidth())
        self.y_Label.setSizePolicy(sizePolicy)
        self.y_Label.setMinimumSize(QtCore.QSize(25, 25))
        self.y_Label.setMaximumSize(QtCore.QSize(25, 25))
        self.y_Label.setObjectName("y_Label")
        self.gridLayout_3.addWidget(self.y_Label, 4, 0, 1, 1)

        self.x_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_Label.sizePolicy().hasHeightForWidth())
        self.x_Label.setSizePolicy(sizePolicy)
        self.x_Label.setMinimumSize(QtCore.QSize(25, 25))
        self.x_Label.setMaximumSize(QtCore.QSize(25, 25))
        self.x_Label.setObjectName("x_Label")
        self.gridLayout_3.addWidget(self.x_Label, 3, 0, 1, 1)

        self.click_1_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_1_Y.sizePolicy().hasHeightForWidth())
        self.click_1_Y.setSizePolicy(sizePolicy)
        self.click_1_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.click_1_Y.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.click_1_Y.setFont(font)
        self.click_1_Y.setObjectName("click_1_Y")
        self.gridLayout_3.addWidget(self.click_1_Y, 4, 2, 1, 1)

        self.current_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_X.sizePolicy().hasHeightForWidth())
        self.current_X.setSizePolicy(sizePolicy)
        self.current_X.setMinimumSize(QtCore.QSize(120, 20))
        self.current_X.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.current_X.setFont(font)
        self.current_X.setObjectName("current_X")
        self.gridLayout_3.addWidget(self.current_X, 3, 1, 1, 1)

        self.click2_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click2_Label.sizePolicy().hasHeightForWidth())
        self.click2_Label.setSizePolicy(sizePolicy)
        self.click2_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.click2_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.click2_Label.setObjectName("click2_Label")
        self.gridLayout_3.addWidget(self.click2_Label, 2, 3, 1, 1)

        self.click_2_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_2_X.sizePolicy().hasHeightForWidth())
        self.click_2_X.setSizePolicy(sizePolicy)
        self.click_2_X.setMinimumSize(QtCore.QSize(120, 20))
        self.click_2_X.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.click_2_X.setFont(font)
        self.click_2_X.setObjectName("click_2_X")
        self.gridLayout_3.addWidget(self.click_2_X, 3, 3, 1, 1)

        self.button_ClearDeltas = QtWidgets.QPushButton(self.tab_Deltas)
        self.button_ClearDeltas.setObjectName("button_ClearDeltas")
        self.gridLayout_3.addWidget(self.button_ClearDeltas, 1, 3, 1, 1)

        self.option_Deltas = QtWidgets.QCheckBox(self.tab_Deltas)
        self.option_Deltas.setObjectName("option_Deltas")
        self.gridLayout_3.addWidget(self.option_Deltas, 1, 2, 1, 1)

        self.option_Cursor = QtWidgets.QCheckBox(self.tab_Deltas)
        self.option_Cursor.setMaximumSize(QtCore.QSize(16777215, 20))
        self.option_Cursor.setObjectName("option_Cursor")
        self.gridLayout_3.addWidget(self.option_Cursor, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)

        self.cursors_Tabber.addTab(self.tab_Deltas, "")


####################################################################################
# left-lower area tab2 : integrate
####################################################################################
        self.tab_Integrals = QtWidgets.QWidget()
        self.tab_Integrals.setObjectName("tab_Integrals")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_Integrals)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_6 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)

        self.integral_Width = QtWidgets.QLineEdit(self.tab_Integrals)
        self.integral_Width.setObjectName("integral_Width")
        self.gridLayout_15.addWidget(self.integral_Width, 0, 1, 1, 1)

        self.button_IntegralWidth = QtWidgets.QPushButton(self.tab_Integrals)
        self.button_IntegralWidth.setMinimumSize(QtCore.QSize(0, 20))
        self.button_IntegralWidth.setMaximumSize(QtCore.QSize(16777215, 20))
        self.button_IntegralWidth.setObjectName("button_IntegralWidth")
        self.gridLayout_15.addWidget(self.button_IntegralWidth, 1, 1, 1, 1)

        self.verticalLayout_2.addLayout(self.gridLayout_15)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.option_ShowBars = QtWidgets.QCheckBox(self.tab_Integrals)
        self.option_ShowBars.setChecked(True)
        self.option_ShowBars.setObjectName("option_ShowBars")
        self.gridLayout_16.addWidget(self.option_ShowBars, 0, 0, 1, 1)

        self.button_ClearIntegrals = QtWidgets.QPushButton(self.tab_Integrals)
        self.button_ClearIntegrals.setMinimumSize(QtCore.QSize(0, 20))
        self.button_ClearIntegrals.setMaximumSize(QtCore.QSize(16777215, 20))
        self.button_ClearIntegrals.setObjectName("button_ClearIntegrals")
        self.gridLayout_16.addWidget(self.button_ClearIntegrals, 0, 1, 1, 1)

        self.verticalLayout_2.addLayout(self.gridLayout_16)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.normalize_Magenta = QtWidgets.QRadioButton(self.tab_Integrals)
        self.normalize_Magenta.setMaximumSize(QtCore.QSize(16777215, 14))
        self.normalize_Magenta.setText("")
        self.normalize_Magenta.setObjectName("normalize_Magenta")
        self.gridLayout_13.addWidget(self.normalize_Magenta, 5, 8, 1, 1)

        self.integral_Green = QtWidgets.QLineEdit(self.tab_Integrals)
        self.integral_Green.setMinimumSize(QtCore.QSize(100, 0))
        self.integral_Green.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.integral_Green.setFont(font)
        self.integral_Green.setObjectName("integral_Green")
        self.gridLayout_13.addWidget(self.integral_Green, 1, 3, 1, 2)

        self.label_4 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 5, 1, 1)

        self.normalize_Blue = QtWidgets.QRadioButton(self.tab_Integrals)
        self.normalize_Blue.setMaximumSize(QtCore.QSize(16777215, 14))
        self.normalize_Blue.setText("")
        self.normalize_Blue.setObjectName("normalize_Blue")
        self.gridLayout_13.addWidget(self.normalize_Blue, 5, 6, 1, 1)

        self.max_Blue = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Blue.setMinimumSize(QtCore.QSize(100, 0))
        self.max_Blue.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Blue.setFont(font)
        self.max_Blue.setObjectName("max_Blue")
        self.gridLayout_13.addWidget(self.max_Blue, 2, 5, 1, 2)

        self.label_3 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 0, 3, 1, 1)

        self.label_9 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 5, 0, 1, 1)

        self.max_Red = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Red.setMinimumSize(QtCore.QSize(100, 0))
        self.max_Red.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Red.setFont(font)
        self.max_Red.setObjectName("max_Red")
        self.gridLayout_13.addWidget(self.max_Red, 2, 1, 1, 2)

        self.fwhm_Green = QtWidgets.QLineEdit(self.tab_Integrals)
        self.fwhm_Green.setMinimumSize(QtCore.QSize(100, 0))
        self.fwhm_Green.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwhm_Green.setFont(font)
        self.fwhm_Green.setObjectName("fwhm_Green")
        self.gridLayout_13.addWidget(self.fwhm_Green, 4, 3, 1, 2)

        self.fwhm_Blue = QtWidgets.QLineEdit(self.tab_Integrals)
        self.fwhm_Blue.setMinimumSize(QtCore.QSize(100, 0))
        self.fwhm_Blue.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwhm_Blue.setFont(font)
        self.fwhm_Blue.setObjectName("fwhm_Blue")
        self.gridLayout_13.addWidget(self.fwhm_Blue, 4, 5, 1, 2)

        self.normalize_Red = QtWidgets.QRadioButton(self.tab_Integrals)
        self.normalize_Red.setMaximumSize(QtCore.QSize(16777215, 14))
        self.normalize_Red.setText("")
        self.normalize_Red.setObjectName("normalize_Red")
        self.gridLayout_13.addWidget(self.normalize_Red, 5, 2, 1, 1)

        self.integral_Blue = QtWidgets.QLineEdit(self.tab_Integrals)
        self.integral_Blue.setMinimumSize(QtCore.QSize(100, 0))
        self.integral_Blue.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.integral_Blue.setFont(font)
        self.integral_Blue.setObjectName("integral_Blue")
        self.gridLayout_13.addWidget(self.integral_Blue, 1, 5, 1, 2)

        self.label_11 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 4, 0, 1, 1)

        self.max_Pos_Red = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Pos_Red.setMinimumSize(QtCore.QSize(100, 20))
        self.max_Pos_Red.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Pos_Red.setFont(font)
        self.max_Pos_Red.setObjectName("max_Pos_Red")
        self.gridLayout_13.addWidget(self.max_Pos_Red, 3, 1, 1, 2)

        self.label_8 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 2, 0, 1, 1)

        self.label_7 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 1, 0, 1, 1)

        self.integral_Red = QtWidgets.QLineEdit(self.tab_Integrals)
        self.integral_Red.setMinimumSize(QtCore.QSize(100, 0))
        self.integral_Red.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.integral_Red.setFont(font)
        self.integral_Red.setObjectName("integral_Red")
        self.gridLayout_13.addWidget(self.integral_Red, 1, 1, 1, 2)

        self.normalize_Green = QtWidgets.QRadioButton(self.tab_Integrals)
        self.normalize_Green.setMaximumSize(QtCore.QSize(16777215, 14))
        self.normalize_Green.setText("")
        self.normalize_Green.setObjectName("normalize_Green")
        self.gridLayout_13.addWidget(self.normalize_Green, 5, 4, 1, 1)

        self.label_17 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_17.setObjectName("label_17")
        self.gridLayout_13.addWidget(self.label_17, 3, 0, 1, 1)

        self.max_Magenta = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Magenta.setMinimumSize(QtCore.QSize(100, 0))
        self.max_Magenta.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Magenta.setFont(font)
        self.max_Magenta.setObjectName("max_Magenta")
        self.gridLayout_13.addWidget(self.max_Magenta, 2, 7, 1, 2)

        self.fwhm_Magenta = QtWidgets.QLineEdit(self.tab_Integrals)
        self.fwhm_Magenta.setMinimumSize(QtCore.QSize(100, 0))
        self.fwhm_Magenta.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwhm_Magenta.setFont(font)
        self.fwhm_Magenta.setObjectName("fwhm_Magenta")
        self.gridLayout_13.addWidget(self.fwhm_Magenta, 4, 7, 1, 2)

        self.label = QtWidgets.QLabel(self.tab_Integrals)
        self.label.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 0, 1, 1, 1)

        self.max_Pos_Green = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Pos_Green.setMinimumSize(QtCore.QSize(100, 20))
        self.max_Pos_Green.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Pos_Green.setFont(font)
        self.max_Pos_Green.setObjectName("max_Pos_Green")
        self.gridLayout_13.addWidget(self.max_Pos_Green, 3, 3, 1, 2)

        self.label_5 = QtWidgets.QLabel(self.tab_Integrals)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 14))
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 0, 7, 1, 1)

        self.fwhm_Red = QtWidgets.QLineEdit(self.tab_Integrals)
        self.fwhm_Red.setMinimumSize(QtCore.QSize(100, 0))
        self.fwhm_Red.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fwhm_Red.setFont(font)
        self.fwhm_Red.setObjectName("fwhm_Red")
        self.gridLayout_13.addWidget(self.fwhm_Red, 4, 1, 1, 2)

        self.max_Pos_Magenta = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Pos_Magenta.setMinimumSize(QtCore.QSize(100, 20))
        self.max_Pos_Magenta.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Pos_Magenta.setFont(font)
        self.max_Pos_Magenta.setObjectName("max_Pos_Magenta")
        self.gridLayout_13.addWidget(self.max_Pos_Magenta, 3, 7, 1, 2)

        self.normalize_Off = QtWidgets.QRadioButton(self.tab_Integrals)
        self.normalize_Off.setMaximumSize(QtCore.QSize(16777215, 20))
        self.normalize_Off.setChecked(True)
        self.normalize_Off.setObjectName("normalize_Off")
        self.gridLayout_13.addWidget(self.normalize_Off, 5, 9, 1, 1)

        self.max_Green = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Green.setMinimumSize(QtCore.QSize(100, 0))
        self.max_Green.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Green.setFont(font)
        self.max_Green.setObjectName("max_Green")
        self.gridLayout_13.addWidget(self.max_Green, 2, 3, 1, 2)

        self.max_Pos_Blue = QtWidgets.QLineEdit(self.tab_Integrals)
        self.max_Pos_Blue.setMinimumSize(QtCore.QSize(100, 20))
        self.max_Pos_Blue.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_Pos_Blue.setFont(font)
        self.max_Pos_Blue.setObjectName("max_Pos_Blue")
        self.gridLayout_13.addWidget(self.max_Pos_Blue, 3, 5, 1, 2)

        self.integral_Magenta = QtWidgets.QLineEdit(self.tab_Integrals)
        self.integral_Magenta.setMinimumSize(QtCore.QSize(100, 0))
        self.integral_Magenta.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.integral_Magenta.setFont(font)
        self.integral_Magenta.setObjectName("integral_Magenta")
        self.gridLayout_13.addWidget(self.integral_Magenta, 1, 7, 1, 2)

        self.horizontalLayout_4.addLayout(self.gridLayout_13)
        self.cursors_Tabber.addTab(self.tab_Integrals, "")

####################################################################################
# left-lower area tab3 : counts
####################################################################################
        self.tab_Counts = QtWidgets.QWidget()
        self.tab_Counts.setObjectName("tab_Counts")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_Counts)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.tab_Counts)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 1, 0, 1, 1)

        self.counts_Ch1_Big = QtWidgets.QLineEdit(self.tab_Counts)
        self.counts_Ch1_Big.setMinimumSize(QtCore.QSize(300, 0))
        self.counts_Ch1_Big.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.counts_Ch1_Big.setFont(font)
        self.counts_Ch1_Big.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.counts_Ch1_Big.setObjectName("counts_Ch1_Big")
        self.gridLayout_9.addWidget(self.counts_Ch1_Big, 1, 1, 1, 1)

        self.counts_Ch0_Big = QtWidgets.QLineEdit(self.tab_Counts)
        self.counts_Ch0_Big.setMinimumSize(QtCore.QSize(240, 0))
        self.counts_Ch0_Big.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.counts_Ch0_Big.setFont(font)
        self.counts_Ch0_Big.setFrame(True)
        self.counts_Ch0_Big.setCursorPosition(0)
        self.counts_Ch0_Big.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.counts_Ch0_Big.setObjectName("counts_Ch0_Big")
        self.gridLayout_9.addWidget(self.counts_Ch0_Big, 0, 1, 1, 1)

        self.label_13 = QtWidgets.QLabel(self.tab_Counts)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 1)
        self.option_Ch0_Counts = QtWidgets.QCheckBox(self.tab_Counts)
        self.option_Ch0_Counts.setObjectName("option_Ch0_Counts")
        self.gridLayout_9.addWidget(self.option_Ch0_Counts, 0, 2, 1, 1)

        self.option_Ch1_Counts = QtWidgets.QCheckBox(self.tab_Counts)
        self.option_Ch1_Counts.setChecked(True)
        self.option_Ch1_Counts.setObjectName("option_Ch1_Counts")
        self.gridLayout_9.addWidget(self.option_Ch1_Counts, 1, 2, 1, 1)

        self.gridLayout_12.addLayout(self.gridLayout_9, 0, 0, 1, 1)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 1, 1, 1)

        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Counts)
        self.groupBox_2.setMinimumSize(QtCore.QSize(170, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setMinimumSize(QtCore.QSize(60, 0))
        self.label_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 2, 0, 1, 1)

        self.value_NumGraphCounts = QtWidgets.QSpinBox(self.groupBox_2)
        self.value_NumGraphCounts.setMaximum(100000)
        self.value_NumGraphCounts.setProperty("value", 100)
        self.value_NumGraphCounts.setObjectName("value_NumGraphCounts")
        self.gridLayout_14.addWidget(self.value_NumGraphCounts, 3, 1, 1, 1)

        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 3, 0, 1, 1)

        self.option_SciCounts = QtWidgets.QCheckBox(self.groupBox_2)
        self.option_SciCounts.setMinimumSize(QtCore.QSize(75, 0))
        self.option_SciCounts.setMaximumSize(QtCore.QSize(75, 16777215))
        self.option_SciCounts.setObjectName("option_SciCounts")
        self.gridLayout_14.addWidget(self.option_SciCounts, 1, 1, 1, 1)

        self.value_CountPrecision = QtWidgets.QSpinBox(self.groupBox_2)
        self.value_CountPrecision.setMinimumSize(QtCore.QSize(55, 0))
        self.value_CountPrecision.setMaximumSize(QtCore.QSize(55, 16777215))
        self.value_CountPrecision.setMaximum(12)
        self.value_CountPrecision.setProperty("value", 3)
        self.value_CountPrecision.setObjectName("value_CountPrecision")
        self.gridLayout_14.addWidget(self.value_CountPrecision, 2, 1, 1, 1)

        self.button_CountsReset = QtWidgets.QPushButton(self.groupBox_2)
        self.button_CountsReset.setObjectName("button_CountsReset")
        self.gridLayout_14.addWidget(self.button_CountsReset, 4, 0, 1, 2)

        self.gridLayout_12.addWidget(self.groupBox_2, 0, 2, 1, 1)

        self.cursors_Tabber.addTab(self.tab_Counts, "")

        self.horizontalLayout_5.addWidget(self.cursors_Tabber)

####################################################################################
# left-lower area tab4 : Autosave
####################################################################################
        self.tab_Auto = QtWidgets.QWidget()
        self.tab_Auto.setObjectName("tab_Auto")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab_Auto)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")

        self.histo_Label = QtWidgets.QLabel(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histo_Label.sizePolicy().hasHeightForWidth())
        self.histo_Label.setSizePolicy(sizePolicy)
        self.histo_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.histo_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.histo_Label.setObjectName("histo_Label")
        self.gridLayout_21.addWidget(self.histo_Label, 1, 1, 1, 1)

        self.histoTime = QtWidgets.QLineEdit(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histoTime.sizePolicy().hasHeightForWidth())
        self.histoTime.setSizePolicy(sizePolicy)
        self.histoTime.setMinimumSize(QtCore.QSize(200, 20))
        self.histoTime.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.histoTime.setFont(font)
        self.histoTime.setObjectName("histoTime")
        self.gridLayout_21.addWidget(self.histoTime, 1, 2, 1, 1)

        self.elapsed_Label = QtWidgets.QLabel(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsed_Label.sizePolicy().hasHeightForWidth())
        self.elapsed_Label.setSizePolicy(sizePolicy)
        self.elapsed_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.elapsed_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.elapsed_Label.setObjectName("elapsed_Label")
        self.gridLayout_21.addWidget(self.elapsed_Label, 2, 1, 1, 1)

        self.elapsedTime = QtWidgets.QLineEdit(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsedTime.sizePolicy().hasHeightForWidth())
        self.elapsedTime.setSizePolicy(sizePolicy)
        self.elapsedTime.setMinimumSize(QtCore.QSize(200, 20))
        self.elapsedTime.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.elapsedTime.setFont(font)
        self.elapsedTime.setObjectName("elapsedTime")
        self.gridLayout_21.addWidget(self.elapsedTime, 2, 2, 1, 1)

        self.output_Label = QtWidgets.QLabel(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_Label.sizePolicy().hasHeightForWidth())
        self.output_Label.setSizePolicy(sizePolicy)
        self.output_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.output_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.output_Label.setObjectName("output_Label")
        self.gridLayout_21.addWidget(self.output_Label, 3, 1, 1, 1)

        self.output_File = QtWidgets.QLineEdit(self.tab_Auto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_File.sizePolicy().hasHeightForWidth())
        self.output_File.setSizePolicy(sizePolicy)
        self.output_File.setMinimumSize(QtCore.QSize(200, 20))
        self.output_File.setMaximumSize(QtCore.QSize(200, 20))
#        font = QtGui.QFont()
#        font.setPointSize(12)
#        self.output_File.setFont(font)
        self.output_File.setObjectName("output_File")
        self.gridLayout_21.addWidget(self.output_File, 3, 2, 1, 1)

        self.button_AutoStart = QtWidgets.QPushButton(self.tab_Auto)
        self.button_AutoStart.setObjectName("button_AutoStart")
        self.button_AutoStart.setMinimumSize(QtCore.QSize(120, 20))
        self.button_AutoStart.setMaximumSize(QtCore.QSize(120, 20))
        self.gridLayout_21.addWidget(self.button_AutoStart, 3, 3, 1, 1)
        self.button_AutoStop = QtWidgets.QPushButton(self.tab_Auto)
        self.button_AutoStop.setObjectName("button_AutoStop")
        self.button_AutoStop.setMaximumSize(QtCore.QSize(16777215, 25))
        self.button_AutoStop.setMinimumSize(QtCore.QSize(120, 20))
        self.button_AutoStop.setMaximumSize(QtCore.QSize(120, 20))
        self.gridLayout_21.addWidget(self.button_AutoStop, 3, 4, 1, 1)

        self.gridLayout_20.addLayout(self.gridLayout_21, 0, 1, 1, 1)
        self.cursors_Tabber.addTab(self.tab_Auto, "")


        spacerItem2 = QtWidgets.QSpacerItem(243, 88, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)


####################################################################################
# Right Column
####################################################################################
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(280, 550))
        self.frame.setMaximumSize(QtCore.QSize(280, 550))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setMinimumSize(QtCore.QSize(260, 160))
        self.tabWidget.setMaximumSize(QtCore.QSize(260, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CFD0_Zerocross_Label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Zerocross_Label.sizePolicy().hasHeightForWidth())
        self.CFD0_Zerocross_Label.setSizePolicy(sizePolicy)
        self.CFD0_Zerocross_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD0_Zerocross_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD0_Zerocross_Label.setObjectName("CFD0_Zerocross_Label")
        self.gridLayout_6.addWidget(self.CFD0_Zerocross_Label, 0, 0, 1, 1)
        self.CFD0_Zerocross = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Zerocross.sizePolicy().hasHeightForWidth())
        self.CFD0_Zerocross.setSizePolicy(sizePolicy)
        self.CFD0_Zerocross.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD0_Zerocross.setMinimum(1)
        self.CFD0_Zerocross.setMaximum(20)
        self.CFD0_Zerocross.setProperty("value", 10)
        self.CFD0_Zerocross.setObjectName("CFD0_Zerocross")
        self.gridLayout_6.addWidget(self.CFD0_Zerocross, 0, 1, 1, 1)
        self.CFD0_Level_Label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Level_Label.sizePolicy().hasHeightForWidth())
        self.CFD0_Level_Label.setSizePolicy(sizePolicy)
        self.CFD0_Level_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD0_Level_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD0_Level_Label.setObjectName("CFD0_Level_Label")
        self.gridLayout_6.addWidget(self.CFD0_Level_Label, 1, 0, 1, 1)
        self.CFD0_Level = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Level.sizePolicy().hasHeightForWidth())
        self.CFD0_Level.setSizePolicy(sizePolicy)
        self.CFD0_Level.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD0_Level.setMinimum(1)
        self.CFD0_Level.setMaximum(800)
        self.CFD0_Level.setProperty("value", 50)
        self.CFD0_Level.setObjectName("CFD0_Level")
        self.gridLayout_6.addWidget(self.CFD0_Level, 1, 1, 1, 1)
        self.sync_Divider_Label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Divider_Label.sizePolicy().hasHeightForWidth())
        self.sync_Divider_Label.setSizePolicy(sizePolicy)
        self.sync_Divider_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.sync_Divider_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.sync_Divider_Label.setObjectName("sync_Divider_Label")
        self.gridLayout_6.addWidget(self.sync_Divider_Label, 2, 0, 1, 1)
        self.sync_Divider = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Divider.sizePolicy().hasHeightForWidth())
        self.sync_Divider.setSizePolicy(sizePolicy)
        self.sync_Divider.setMinimumSize(QtCore.QSize(50, 0))
        self.sync_Divider.setObjectName("sync_Divider")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.gridLayout_6.addWidget(self.sync_Divider, 2, 1, 1, 1)
        self.sync_Offset_Label = QtWidgets.QLabel(self.tab)
        self.sync_Offset_Label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Offset_Label.sizePolicy().hasHeightForWidth())
        self.sync_Offset_Label.setSizePolicy(sizePolicy)
        self.sync_Offset_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.sync_Offset_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.sync_Offset_Label.setObjectName("sync_Offset_Label")
        self.gridLayout_6.addWidget(self.sync_Offset_Label, 3, 0, 1, 1)
        self.sync_Offset = QtWidgets.QSpinBox(self.tab)
        self.sync_Offset.setEnabled(False)
        self.sync_Offset.setObjectName("sync_Offset")
        self.gridLayout_6.addWidget(self.sync_Offset, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.CFD1_Zerocross_Label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD1_Zerocross_Label.sizePolicy().hasHeightForWidth())
        self.CFD1_Zerocross_Label.setSizePolicy(sizePolicy)
        self.CFD1_Zerocross_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD1_Zerocross_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD1_Zerocross_Label.setObjectName("CFD1_Zerocross_Label")
        self.gridLayout_7.addWidget(self.CFD1_Zerocross_Label, 0, 0, 1, 1)
        self.CFD1_Zerocross = QtWidgets.QSpinBox(self.tab_2)
        self.CFD1_Zerocross.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD1_Zerocross.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CFD1_Zerocross.setMaximum(20)
        self.CFD1_Zerocross.setProperty("value", 10)
        self.CFD1_Zerocross.setObjectName("CFD1_Zerocross")
        self.gridLayout_7.addWidget(self.CFD1_Zerocross, 0, 1, 1, 1)
        self.CFD1_Level_Label = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD1_Level_Label.sizePolicy().hasHeightForWidth())
        self.CFD1_Level_Label.setSizePolicy(sizePolicy)
        self.CFD1_Level_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD1_Level_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD1_Level_Label.setObjectName("CFD1_Level_Label")
        self.gridLayout_7.addWidget(self.CFD1_Level_Label, 1, 0, 1, 1)
        self.CFD1_Level = QtWidgets.QSpinBox(self.tab_2)
        self.CFD1_Level.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD1_Level.setMaximumSize(QtCore.QSize(50, 16777215))
        self.CFD1_Level.setMaximum(800)
        self.CFD1_Level.setProperty("value", 50)
        self.CFD1_Level.setObjectName("CFD1_Level")
        self.gridLayout_7.addWidget(self.CFD1_Level, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget)

        self.general_Box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_Box.sizePolicy().hasHeightForWidth())
        self.general_Box.setSizePolicy(sizePolicy)
        self.general_Box.setMinimumSize(QtCore.QSize(260, 100))
        self.general_Box.setMaximumSize(QtCore.QSize(260, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.general_Box.setFont(font)
        self.general_Box.setObjectName("general_Box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.general_Box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.general_Layout = QtWidgets.QGridLayout()
        self.general_Layout.setObjectName("general_Layout")
        self.resolution_Label = QtWidgets.QLabel(self.general_Box)
        self.resolution_Label.setObjectName("resolution_Label")
        self.general_Layout.addWidget(self.resolution_Label, 0, 0, 1, 1)
        self.acq_Time = QtWidgets.QSpinBox(self.general_Box)
        self.acq_Time.setMaximum(36000000)
        self.acq_Time.setProperty("value", 1000)
        self.acq_Time.setObjectName("acq_Time")
        self.general_Layout.addWidget(self.acq_Time, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_Box)
        self.label_2.setObjectName("label_2")
        self.general_Layout.addWidget(self.label_2, 1, 0, 1, 1)
        self.resolution = QtWidgets.QComboBox(self.general_Box)
        self.resolution.setObjectName("resolution")
        self.general_Layout.addWidget(self.resolution, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.general_Layout)
        self.verticalLayout_4.addWidget(self.general_Box)

        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMinimumSize(QtCore.QSize(260, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(260, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.existing_inis = QtWidgets.QComboBox(self.groupBox)
        self.existing_inis.setObjectName("existing_inis")
        self.horizontalLayout_2.addWidget(self.existing_inis)
        self.button_LoadSettings = QtWidgets.QPushButton(self.groupBox)
        self.button_LoadSettings.setMinimumSize(QtCore.QSize(65, 0))
        self.button_LoadSettings.setMaximumSize(QtCore.QSize(65, 16777215))
        self.button_LoadSettings.setObjectName("button_LoadSettings")
        self.horizontalLayout_2.addWidget(self.button_LoadSettings)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.settings_SaveName = QtWidgets.QLineEdit(self.groupBox)
        self.settings_SaveName.setObjectName("settings_SaveName")
        self.horizontalLayout_3.addWidget(self.settings_SaveName)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.button_SaveSettings = QtWidgets.QPushButton(self.groupBox)
        self.button_SaveSettings.setMinimumSize(QtCore.QSize(65, 0))
        self.button_SaveSettings.setMaximumSize(QtCore.QSize(65, 16777215))
        self.button_SaveSettings.setObjectName("button_SaveSettings")
        self.horizontalLayout_3.addWidget(self.button_SaveSettings)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        """self.button_Defaults = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Defaults.sizePolicy().hasHeightForWidth())
        self.button_Defaults.setSizePolicy(sizePolicy)
        self.button_Defaults.setMinimumSize(QtCore.QSize(50, 25))
        self.button_Defaults.setMaximumSize(QtCore.QSize(200, 25))
        self.button_Defaults.setObjectName("button_Defaults")
        self.verticalLayout_5.addWidget(self.button_Defaults)"""
        self.verticalLayout_4.addWidget(self.groupBox)

        self.histogram_Box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_Box.sizePolicy().hasHeightForWidth())
        self.histogram_Box.setSizePolicy(sizePolicy)
        self.histogram_Box.setMinimumSize(QtCore.QSize(260, 140))
        self.histogram_Box.setMaximumSize(QtCore.QSize(260, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.histogram_Box.setFont(font)
        self.histogram_Box.setObjectName("histogram_Box")
        self.gridLayout = QtWidgets.QGridLayout(self.histogram_Box)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.option_Cumulative = QtWidgets.QCheckBox(self.histogram_Box)
        self.option_Cumulative.setObjectName("option_Cumulative")
        self.gridLayout_5.addWidget(self.option_Cumulative, 0, 0, 1, 1)
        self.option_LogY = QtWidgets.QCheckBox(self.histogram_Box)
        self.option_LogY.setObjectName("option_LogY")
        self.gridLayout_5.addWidget(self.option_LogY, 0, 1, 1, 1)
        self.button_AutoRange = QtWidgets.QPushButton(self.histogram_Box)
        self.button_AutoRange.setMaximumSize(QtCore.QSize(16777215, 25))
        self.button_AutoRange.setObjectName("button_AutoRange")
        self.gridLayout_5.addWidget(self.button_AutoRange, 0, 2, 1, 1)
        self.label_max_t = QtWidgets.QLabel(self.histogram_Box)
        self.label_max_t.setObjectName("label_max_t")
        self.gridLayout_5.addWidget(self.label_max_t, 1, 0, 1, 1)
        self.max_t = QtWidgets.QLineEdit(self.histogram_Box)
        self.max_t.setObjectName("max_t")
        self.gridLayout_5.addWidget(self.max_t, 1, 1, 1, 1)
        """self.button_ClearHistogram = QtWidgets.QPushButton(self.histogram_Box)
        self.button_ClearHistogram.setMaximumSize(QtCore.QSize(16777215, 30))
        self.button_ClearHistogram.setObjectName("button_ClearHistogram")
        self.gridLayout_5.addWidget(self.button_ClearHistogram, 2, 1, 1, 1)"""
        self.data_Filename = QtWidgets.QLineEdit(self.histogram_Box)
        self.data_Filename.setObjectName("data_Filename")
        self.gridLayout_5.addWidget(self.data_Filename, 2, 0, 1, 2)
        self.button_SaveHisto = QtWidgets.QPushButton(self.histogram_Box)
        self.button_SaveHisto.setMaximumSize(QtCore.QSize(16777215, 25))
        self.button_SaveHisto.setObjectName("button_SaveHisto")
        self.gridLayout_5.addWidget(self.button_SaveHisto, 2, 2, 1, 1)
        #self.filename_Label = QtWidgets.QLabel(self.histogram_Box)
        #self.filename_Label.setObjectName("filename_Label")
        #self.gridLayout_5.addWidget(self.filename_Label, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.histogram_Box)


        self.verticalLayout_6.addWidget(self.frame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.control_Warning_Tabber = QtWidgets.QTabWidget(self.centralwidget)
        self.control_Warning_Tabber.setObjectName("control_Warning_Tabber")
        self.controls_Tab = QtWidgets.QWidget()
        self.controls_Tab.setObjectName("controls_Tab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.controls_Tab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.controls_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(130, 120))
        self.groupBox_3.setMaximumSize(QtCore.QSize(120, 160))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_11.setVerticalSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setHorizontalSpacing(0)
        self.gridLayout_10.setVerticalSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_ApplySettings = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ApplySettings.sizePolicy().hasHeightForWidth())
        self.button_ApplySettings.setSizePolicy(sizePolicy)
        self.button_ApplySettings.setMinimumSize(QtCore.QSize(100, 20))
        self.button_ApplySettings.setMaximumSize(QtCore.QSize(100, 20))
        self.button_ApplySettings.setObjectName("button_ApplySettings")
        self.gridLayout_10.addWidget(self.button_ApplySettings, 0, 0, 1, 1)
        self.status = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setMinimumSize(QtCore.QSize(100, 20))
        self.status.setMaximumSize(QtCore.QSize(100, 20))
        self.status.setObjectName("status")
        self.gridLayout_10.addWidget(self.status, 2, 0, 1, 1)
        self.button_StartStop = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_StartStop.sizePolicy().hasHeightForWidth())
        self.button_StartStop.setSizePolicy(sizePolicy)
        self.button_StartStop.setMinimumSize(QtCore.QSize(100, 20))
        self.button_StartStop.setMaximumSize(QtCore.QSize(100, 20))
        self.button_StartStop.setObjectName("button_StartStop")
        self.gridLayout_10.addWidget(self.button_StartStop, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.controls_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(130, 120))
        self.groupBox_4.setMaximumSize(QtCore.QSize(130, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.counts_Ch0_Label = QtWidgets.QLabel(self.groupBox_4)
        self.counts_Ch0_Label.setMinimumSize(QtCore.QSize(0, 15))
        self.counts_Ch0_Label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.counts_Ch0_Label.setObjectName("counts_Ch0_Label")
        self.verticalLayout_3.addWidget(self.counts_Ch0_Label)
        self.counts_Ch0 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counts_Ch0.sizePolicy().hasHeightForWidth())
        self.counts_Ch0.setSizePolicy(sizePolicy)
        self.counts_Ch0.setMinimumSize(QtCore.QSize(100, 20))
        self.counts_Ch0.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.counts_Ch0.setFont(font)
        self.counts_Ch0.setObjectName("counts_Ch0")
        self.verticalLayout_3.addWidget(self.counts_Ch0)
        self.counts_Ch1_Label = QtWidgets.QLabel(self.groupBox_4)
        self.counts_Ch1_Label.setMinimumSize(QtCore.QSize(0, 15))
        self.counts_Ch1_Label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.counts_Ch1_Label.setObjectName("counts_Ch1_Label")
        self.verticalLayout_3.addWidget(self.counts_Ch1_Label)
        self.counts_Ch1 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counts_Ch1.sizePolicy().hasHeightForWidth())
        self.counts_Ch1.setSizePolicy(sizePolicy)
        self.counts_Ch1.setMinimumSize(QtCore.QSize(100, 20))
        self.counts_Ch1.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.counts_Ch1.setFont(font)
        self.counts_Ch1.setObjectName("counts_Ch1")
        self.verticalLayout_3.addWidget(self.counts_Ch1)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.control_Warning_Tabber.addTab(self.controls_Tab, "")
        self.warnings_Tab = QtWidgets.QWidget()
        self.warnings_Tab.setObjectName("warnings_Tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.warnings_Tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.warnings_Display = QtWidgets.QTextEdit(self.warnings_Tab)
        self.warnings_Display.setObjectName("warnings_Display")
        self.gridLayout_17.addWidget(self.warnings_Display, 0, 0, 1, 1)
        self.control_Warning_Tabber.addTab(self.warnings_Tab, "")
        self.verticalLayout_6.addWidget(self.control_Warning_Tabber)
        self.label_171 = QtWidgets.QLabel(self.centralwidget)
        self.label_171.setTextFormat(QtCore.Qt.RichText)
        self.label_171.setScaledContents(False)
        self.label_171.setWordWrap(False)
        self.label_171.setObjectName("label_171")
        self.verticalLayout_6.addWidget(self.label_171)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cursors_Tabber.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        self.control_Warning_Tabber.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.deltas_Label.setText(_translate("MainWindow", "Click1 - Click2"))
        self.current_Label.setText(_translate("MainWindow", "Current (yellow)"))
        self.click1_Label.setText(_translate("MainWindow", "Click1 (red)"))
        self.y_Label.setText(_translate("MainWindow", "Y:"))
        self.x_Label.setText(_translate("MainWindow", "X:"))
        self.click2_Label.setText(_translate("MainWindow", "Click2 (green)"))
        self.button_ClearDeltas.setText(_translate("MainWindow", "Clear Deltas"))
        self.option_Deltas.setText(_translate("MainWindow", "Deltas On"))
        self.option_Cursor.setText(_translate("MainWindow", "Cursor On"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Deltas), _translate("MainWindow", "Deltas"))
        self.label_6.setText(_translate("MainWindow", "Integral Width:"))
        self.button_IntegralWidth.setText(_translate("MainWindow", "Apply"))
        self.option_ShowBars.setText(_translate("MainWindow", "Show Bars"))
        self.button_ClearIntegrals.setText(_translate("MainWindow", "Clear Markers"))
        self.label_4.setText(_translate("MainWindow", "Blue"))
        self.label_3.setText(_translate("MainWindow", "Green"))
        self.label_9.setText(_translate("MainWindow", "Normalize:"))
        self.label_11.setText(_translate("MainWindow", "Fit FWHM:"))
        self.label_8.setText(_translate("MainWindow", "Max:"))
        self.label_7.setText(_translate("MainWindow", "Mean:"))
        self.label_17.setText(_translate("MainWindow", "Max Position:"))
        self.label.setText(_translate("MainWindow", "Red"))
        self.label_5.setText(_translate("MainWindow", "Magenta"))
        self.normalize_Off.setText(_translate("MainWindow", "Off"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Integrals), _translate("MainWindow", "Integrate"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00ff00;\">Ch 1 (signal)</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Ch 0 (sync)</span></p></body></html>"))
        self.option_Ch0_Counts.setText(_translate("MainWindow", "Plot"))
        self.option_Ch1_Counts.setText(_translate("MainWindow", "Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Number Format"))
        self.label_15.setText(_translate("MainWindow", "Precision"))
        self.label_16.setText(_translate("MainWindow", "Graph points"))
        self.option_SciCounts.setText(_translate("MainWindow", "scientific"))
        self.button_CountsReset.setText(_translate("MainWindow", "Reset History"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Counts), _translate("MainWindow", "Counts"))
        self.histo_Label.setText(_translate("MainWindow", "Histo. Time (s)"))
#        self.histoTime.setText(_translate("MainWindow", "300"))
        self.elapsed_Label.setText(_translate("MainWindow", "Elapsed Time (s)"))
        self.elapsedTime.setText(_translate("MainWindow", "0"))
        self.output_Label.setText(_translate("MainWindow", "Output File"))
        self.button_AutoStart.setText(_translate("MainWindow", "Start"))
        self.button_AutoStop.setText(_translate("MainWindow", "Stop"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Auto), _translate("MainWindow", "Autosave"))
        self.CFD0_Zerocross_Label.setText(_translate("MainWindow", "Zero Crossing (mV)"))
        self.CFD0_Level_Label.setText(_translate("MainWindow", "Discriminator (mV)"))
        self.sync_Divider_Label.setText(_translate("MainWindow", "Clock Divider"))
        self.sync_Divider.setItemText(0, _translate("MainWindow", "1"))
        self.sync_Divider.setItemText(1, _translate("MainWindow", "2"))
        self.sync_Divider.setItemText(2, _translate("MainWindow", "4"))
        self.sync_Divider.setItemText(3, _translate("MainWindow", "8"))
        self.sync_Offset_Label.setText(_translate("MainWindow", "Offset (ps)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Channel 0 (sync)"))
        self.CFD1_Zerocross_Label.setText(_translate("MainWindow", "Zero Crossing (mV)"))
        self.CFD1_Level_Label.setText(_translate("MainWindow", "Discriminator (mV)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Channel 1 (signal)"))
        self.general_Box.setTitle(_translate("MainWindow", "General"))
        self.resolution_Label.setText(_translate("MainWindow", "Resolution (ps)"))
        self.label_2.setText(_translate("MainWindow", "Acq. Time (ms)"))
        self.histogram_Box.setTitle(_translate("MainWindow", "Histogram"))
        self.button_SaveHisto.setText(_translate("MainWindow", "Save Histogram"))
        self.data_Filename.setText(_translate("MainWindow", "histogram.csv"))
        #self.filename_Label.setText(_translate("MainWindow", "Save filename:"))
        #self.button_ClearHistogram.setText(_translate("MainWindow", "Clear Histogram"))
        self.label_max_t.setText(_translate("MainWindow", "Maximum Time (ns)"))
        self.option_Cumulative.setText(_translate("MainWindow", "Cumulative"))
        self.button_AutoRange.setText(_translate("MainWindow", "Auto Range"))
        self.option_LogY.setText(_translate("MainWindow", "Log Y"))
        self.groupBox.setTitle(_translate("MainWindow", "Save/Load Settings"))
        self.button_LoadSettings.setText(_translate("MainWindow", "Load"))
        self.label_10.setText(_translate("MainWindow", "Filename:"))
        self.label_12.setText(_translate("MainWindow", ".ini"))
        self.button_SaveSettings.setText(_translate("MainWindow", "Save"))
        #self.button_Defaults.setText(_translate("MainWindow", "Set to defaults"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Controls"))
        self.button_ApplySettings.setText(_translate("MainWindow", "Apply Settings"))
        self.button_StartStop.setText(_translate("MainWindow", "Start/Stop"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Channel Counts"))
        self.counts_Ch0_Label.setText(_translate("MainWindow", "Ch0 (sync)"))
        self.counts_Ch1_Label.setText(_translate("MainWindow", "Ch1 (signal)"))
        self.control_Warning_Tabber.setTabText(self.control_Warning_Tabber.indexOf(self.controls_Tab), _translate("MainWindow", "Controls"))
        self.control_Warning_Tabber.setTabText(self.control_Warning_Tabber.indexOf(self.warnings_Tab), _translate("MainWindow", "Warnings"))
        self.label_171.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Source code and some docs available at: <br/><a href=\"github.com/dldlowndes/LD_Pharppy\"><span style=\" text-decoration: underline; color:#007af4;\">github.com/dldlowndes/LD_Pharppy</span></a><br/>Version 1.0</p></body></html>"))
from pyqtgraph import PlotWidget
