# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graph_Widget = PlotWidget(self.centralwidget)
        self.graph_Widget.setObjectName("graph_Widget")
        self.gridLayout.addWidget(self.graph_Widget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(130, 160))
        self.groupBox_3.setMaximumSize(QtCore.QSize(130, 160))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_ApplySettings = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ApplySettings.sizePolicy().hasHeightForWidth())
        self.button_ApplySettings.setSizePolicy(sizePolicy)
        self.button_ApplySettings.setMinimumSize(QtCore.QSize(100, 25))
        self.button_ApplySettings.setMaximumSize(QtCore.QSize(100, 25))
        self.button_ApplySettings.setObjectName("button_ApplySettings")
        self.gridLayout_10.addWidget(self.button_ApplySettings, 0, 0, 1, 1)
        self.button_Defaults = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Defaults.sizePolicy().hasHeightForWidth())
        self.button_Defaults.setSizePolicy(sizePolicy)
        self.button_Defaults.setMinimumSize(QtCore.QSize(100, 25))
        self.button_Defaults.setMaximumSize(QtCore.QSize(100, 25))
        self.button_Defaults.setObjectName("button_Defaults")
        self.gridLayout_10.addWidget(self.button_Defaults, 1, 0, 1, 1)
        self.button_StartStop = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_StartStop.sizePolicy().hasHeightForWidth())
        self.button_StartStop.setSizePolicy(sizePolicy)
        self.button_StartStop.setMinimumSize(QtCore.QSize(100, 25))
        self.button_StartStop.setMaximumSize(QtCore.QSize(100, 25))
        self.button_StartStop.setObjectName("button_StartStop")
        self.gridLayout_10.addWidget(self.button_StartStop, 2, 0, 1, 1)
        self.status = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setMinimumSize(QtCore.QSize(100, 25))
        self.status.setMaximumSize(QtCore.QSize(100, 25))
        self.status.setObjectName("status")
        self.gridLayout_10.addWidget(self.status, 3, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(130, 160))
        self.groupBox_4.setMaximumSize(QtCore.QSize(130, 160))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.counts_Ch0_Label = QtWidgets.QLabel(self.groupBox_4)
        self.counts_Ch0_Label.setObjectName("counts_Ch0_Label")
        self.verticalLayout_3.addWidget(self.counts_Ch0_Label)
        self.counts_Ch0 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counts_Ch0.sizePolicy().hasHeightForWidth())
        self.counts_Ch0.setSizePolicy(sizePolicy)
        self.counts_Ch0.setMinimumSize(QtCore.QSize(100, 25))
        self.counts_Ch0.setMaximumSize(QtCore.QSize(100, 25))
        self.counts_Ch0.setObjectName("counts_Ch0")
        self.verticalLayout_3.addWidget(self.counts_Ch0)
        self.counts_Ch1_Label = QtWidgets.QLabel(self.groupBox_4)
        self.counts_Ch1_Label.setObjectName("counts_Ch1_Label")
        self.verticalLayout_3.addWidget(self.counts_Ch1_Label)
        self.counts_Ch1 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counts_Ch1.sizePolicy().hasHeightForWidth())
        self.counts_Ch1.setSizePolicy(sizePolicy)
        self.counts_Ch1.setMinimumSize(QtCore.QSize(100, 25))
        self.counts_Ch1.setMaximumSize(QtCore.QSize(100, 25))
        self.counts_Ch1.setObjectName("counts_Ch1")
        self.verticalLayout_3.addWidget(self.counts_Ch1)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.settings_Box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_Box.sizePolicy().hasHeightForWidth())
        self.settings_Box.setSizePolicy(sizePolicy)
        self.settings_Box.setMinimumSize(QtCore.QSize(300, 600))
        self.settings_Box.setMaximumSize(QtCore.QSize(300, 580))
        self.settings_Box.setObjectName("settings_Box")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.settings_Box)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.settings_Layout = QtWidgets.QGridLayout()
        self.settings_Layout.setObjectName("settings_Layout")
        self.histogram_Box = QtWidgets.QGroupBox(self.settings_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram_Box.sizePolicy().hasHeightForWidth())
        self.histogram_Box.setSizePolicy(sizePolicy)
        self.histogram_Box.setMinimumSize(QtCore.QSize(250, 200))
        self.histogram_Box.setMaximumSize(QtCore.QSize(250, 200))
        self.histogram_Box.setObjectName("histogram_Box")
        self.layoutWidget = QtWidgets.QWidget(self.histogram_Box)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 25, 225, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_AutoRange = QtWidgets.QPushButton(self.layoutWidget)
        self.button_AutoRange.setObjectName("button_AutoRange")
        self.gridLayout_5.addWidget(self.button_AutoRange, 0, 1, 1, 1)
        self.filename_Label = QtWidgets.QLabel(self.layoutWidget)
        self.filename_Label.setObjectName("filename_Label")
        self.gridLayout_5.addWidget(self.filename_Label, 1, 0, 1, 1)
        self.filename = QtWidgets.QLineEdit(self.layoutWidget)
        self.filename.setObjectName("filename")
        self.gridLayout_5.addWidget(self.filename, 1, 1, 1, 1)
        self.button_ClearHistogram = QtWidgets.QPushButton(self.layoutWidget)
        self.button_ClearHistogram.setObjectName("button_ClearHistogram")
        self.gridLayout_5.addWidget(self.button_ClearHistogram, 2, 0, 1, 1)
        self.button_SaveHisto = QtWidgets.QPushButton(self.layoutWidget)
        self.button_SaveHisto.setObjectName("button_SaveHisto")
        self.gridLayout_5.addWidget(self.button_SaveHisto, 2, 1, 1, 1)
        self.option_Cursor = QtWidgets.QCheckBox(self.layoutWidget)
        self.option_Cursor.setObjectName("option_Cursor")
        self.gridLayout_5.addWidget(self.option_Cursor, 0, 0, 1, 1)
        self.settings_Layout.addWidget(self.histogram_Box, 3, 0, 1, 1)
        self.general_Box = QtWidgets.QGroupBox(self.settings_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.general_Box.sizePolicy().hasHeightForWidth())
        self.general_Box.setSizePolicy(sizePolicy)
        self.general_Box.setMinimumSize(QtCore.QSize(250, 90))
        self.general_Box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.general_Box.setObjectName("general_Box")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.general_Box)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.general_Layout = QtWidgets.QGridLayout()
        self.general_Layout.setObjectName("general_Layout")
        self.resolution_Label = QtWidgets.QLabel(self.general_Box)
        self.resolution_Label.setObjectName("resolution_Label")
        self.general_Layout.addWidget(self.resolution_Label, 0, 0, 1, 1)
        self.resolution = QtWidgets.QComboBox(self.general_Box)
        self.resolution.setObjectName("resolution")
        self.general_Layout.addWidget(self.resolution, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_Box)
        self.label_2.setObjectName("label_2")
        self.general_Layout.addWidget(self.label_2, 1, 0, 1, 1)
        self.acq_Time = QtWidgets.QSpinBox(self.general_Box)
        self.acq_Time.setMaximum(36000000)
        self.acq_Time.setProperty("value", 1000)
        self.acq_Time.setObjectName("acq_Time")
        self.general_Layout.addWidget(self.acq_Time, 1, 1, 1, 1)
        self.gridLayout_12.addLayout(self.general_Layout, 0, 0, 1, 1)
        self.settings_Layout.addWidget(self.general_Box, 2, 0, 1, 1)
        self.ch1_Box = QtWidgets.QGroupBox(self.settings_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1_Box.sizePolicy().hasHeightForWidth())
        self.ch1_Box.setSizePolicy(sizePolicy)
        self.ch1_Box.setMinimumSize(QtCore.QSize(250, 90))
        self.ch1_Box.setMaximumSize(QtCore.QSize(250, 90))
        self.ch1_Box.setObjectName("ch1_Box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ch1_Box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ch1_Layout = QtWidgets.QGridLayout()
        self.ch1_Layout.setObjectName("ch1_Layout")
        self.CFD1_Zerocross = QtWidgets.QSpinBox(self.ch1_Box)
        self.CFD1_Zerocross.setMaximum(20)
        self.CFD1_Zerocross.setProperty("value", 10)
        self.CFD1_Zerocross.setObjectName("CFD1_Zerocross")
        self.ch1_Layout.addWidget(self.CFD1_Zerocross, 0, 1, 1, 1)
        self.CFD1_Level = QtWidgets.QSpinBox(self.ch1_Box)
        self.CFD1_Level.setMaximum(800)
        self.CFD1_Level.setProperty("value", 50)
        self.CFD1_Level.setObjectName("CFD1_Level")
        self.ch1_Layout.addWidget(self.CFD1_Level, 1, 1, 1, 1)
        self.CFD1_Level_Label = QtWidgets.QLabel(self.ch1_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD1_Level_Label.sizePolicy().hasHeightForWidth())
        self.CFD1_Level_Label.setSizePolicy(sizePolicy)
        self.CFD1_Level_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD1_Level_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD1_Level_Label.setObjectName("CFD1_Level_Label")
        self.ch1_Layout.addWidget(self.CFD1_Level_Label, 1, 0, 1, 1)
        self.CFD1_Zerocross_Label = QtWidgets.QLabel(self.ch1_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD1_Zerocross_Label.sizePolicy().hasHeightForWidth())
        self.CFD1_Zerocross_Label.setSizePolicy(sizePolicy)
        self.CFD1_Zerocross_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD1_Zerocross_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD1_Zerocross_Label.setObjectName("CFD1_Zerocross_Label")
        self.ch1_Layout.addWidget(self.CFD1_Zerocross_Label, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.ch1_Layout, 0, 0, 1, 1)
        self.settings_Layout.addWidget(self.ch1_Box, 1, 0, 1, 1)
        self.ch0_Box = QtWidgets.QGroupBox(self.settings_Box)
        self.ch0_Box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch0_Box.sizePolicy().hasHeightForWidth())
        self.ch0_Box.setSizePolicy(sizePolicy)
        self.ch0_Box.setMinimumSize(QtCore.QSize(250, 160))
        self.ch0_Box.setMaximumSize(QtCore.QSize(250, 160))
        self.ch0_Box.setObjectName("ch0_Box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ch0_Box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ch0_Layout = QtWidgets.QGridLayout()
        self.ch0_Layout.setObjectName("ch0_Layout")
        self.CFD0_Zerocross_Label = QtWidgets.QLabel(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Zerocross_Label.sizePolicy().hasHeightForWidth())
        self.CFD0_Zerocross_Label.setSizePolicy(sizePolicy)
        self.CFD0_Zerocross_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD0_Zerocross_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD0_Zerocross_Label.setObjectName("CFD0_Zerocross_Label")
        self.ch0_Layout.addWidget(self.CFD0_Zerocross_Label, 0, 0, 1, 1)
        self.CFD0_Zerocross = QtWidgets.QSpinBox(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Zerocross.sizePolicy().hasHeightForWidth())
        self.CFD0_Zerocross.setSizePolicy(sizePolicy)
        self.CFD0_Zerocross.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD0_Zerocross.setMinimum(1)
        self.CFD0_Zerocross.setMaximum(20)
        self.CFD0_Zerocross.setProperty("value", 10)
        self.CFD0_Zerocross.setObjectName("CFD0_Zerocross")
        self.ch0_Layout.addWidget(self.CFD0_Zerocross, 0, 1, 1, 1)
        self.CFD0_Level_Label = QtWidgets.QLabel(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Level_Label.sizePolicy().hasHeightForWidth())
        self.CFD0_Level_Label.setSizePolicy(sizePolicy)
        self.CFD0_Level_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.CFD0_Level_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.CFD0_Level_Label.setObjectName("CFD0_Level_Label")
        self.ch0_Layout.addWidget(self.CFD0_Level_Label, 1, 0, 1, 1)
        self.CFD0_Level = QtWidgets.QSpinBox(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CFD0_Level.sizePolicy().hasHeightForWidth())
        self.CFD0_Level.setSizePolicy(sizePolicy)
        self.CFD0_Level.setMinimumSize(QtCore.QSize(50, 0))
        self.CFD0_Level.setMinimum(1)
        self.CFD0_Level.setMaximum(800)
        self.CFD0_Level.setProperty("value", 50)
        self.CFD0_Level.setObjectName("CFD0_Level")
        self.ch0_Layout.addWidget(self.CFD0_Level, 1, 1, 1, 1)
        self.sync_Divider_Label = QtWidgets.QLabel(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Divider_Label.sizePolicy().hasHeightForWidth())
        self.sync_Divider_Label.setSizePolicy(sizePolicy)
        self.sync_Divider_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.sync_Divider_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.sync_Divider_Label.setObjectName("sync_Divider_Label")
        self.ch0_Layout.addWidget(self.sync_Divider_Label, 2, 0, 1, 1)
        self.sync_Divider = QtWidgets.QComboBox(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Divider.sizePolicy().hasHeightForWidth())
        self.sync_Divider.setSizePolicy(sizePolicy)
        self.sync_Divider.setMinimumSize(QtCore.QSize(50, 0))
        self.sync_Divider.setObjectName("sync_Divider")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.sync_Divider.addItem("")
        self.ch0_Layout.addWidget(self.sync_Divider, 2, 1, 1, 1)
        self.sync_Offset_Label = QtWidgets.QLabel(self.ch0_Box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sync_Offset_Label.sizePolicy().hasHeightForWidth())
        self.sync_Offset_Label.setSizePolicy(sizePolicy)
        self.sync_Offset_Label.setMinimumSize(QtCore.QSize(100, 25))
        self.sync_Offset_Label.setMaximumSize(QtCore.QSize(100, 25))
        self.sync_Offset_Label.setObjectName("sync_Offset_Label")
        self.ch0_Layout.addWidget(self.sync_Offset_Label, 3, 0, 1, 1)
        self.sync_Offset = QtWidgets.QDoubleSpinBox(self.ch0_Box)
        self.sync_Offset.setObjectName("sync_Offset")
        self.ch0_Layout.addWidget(self.sync_Offset, 3, 1, 1, 1)
        self.gridLayout_6.addLayout(self.ch0_Layout, 0, 0, 1, 1)
        self.settings_Layout.addWidget(self.ch0_Box, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.settings_Layout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.settings_Box, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.cursors_Tabber = QtWidgets.QTabWidget(self.centralwidget)
        self.cursors_Tabber.setMinimumSize(QtCore.QSize(600, 150))
        self.cursors_Tabber.setMaximumSize(QtCore.QSize(600, 150))
        self.cursors_Tabber.setTabPosition(QtWidgets.QTabWidget.West)
        self.cursors_Tabber.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.cursors_Tabber.setObjectName("cursors_Tabber")
        self.tab_Deltas = QtWidgets.QWidget()
        self.tab_Deltas.setObjectName("tab_Deltas")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Deltas)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.current_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_Y.sizePolicy().hasHeightForWidth())
        self.current_Y.setSizePolicy(sizePolicy)
        self.current_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.current_Y.setMaximumSize(QtCore.QSize(120, 20))
        self.current_Y.setObjectName("current_Y")
        self.gridLayout_3.addWidget(self.current_Y, 4, 1, 1, 1)
        self.deltas_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deltas_Label.sizePolicy().hasHeightForWidth())
        self.deltas_Label.setSizePolicy(sizePolicy)
        self.deltas_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.deltas_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.deltas_Label.setObjectName("deltas_Label")
        self.gridLayout_3.addWidget(self.deltas_Label, 2, 4, 1, 1)
        self.click_1_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_1_X.sizePolicy().hasHeightForWidth())
        self.click_1_X.setSizePolicy(sizePolicy)
        self.click_1_X.setMinimumSize(QtCore.QSize(120, 20))
        self.click_1_X.setMaximumSize(QtCore.QSize(120, 20))
        self.click_1_X.setObjectName("click_1_X")
        self.gridLayout_3.addWidget(self.click_1_X, 3, 2, 1, 1)
        self.current_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_Label.sizePolicy().hasHeightForWidth())
        self.current_Label.setSizePolicy(sizePolicy)
        self.current_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.current_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.current_Label.setObjectName("current_Label")
        self.gridLayout_3.addWidget(self.current_Label, 2, 1, 1, 1)
        self.click_2_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_2_Y.sizePolicy().hasHeightForWidth())
        self.click_2_Y.setSizePolicy(sizePolicy)
        self.click_2_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.click_2_Y.setMaximumSize(QtCore.QSize(120, 20))
        self.click_2_Y.setObjectName("click_2_Y")
        self.gridLayout_3.addWidget(self.click_2_Y, 4, 3, 1, 1)
        self.delta_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delta_Y.sizePolicy().hasHeightForWidth())
        self.delta_Y.setSizePolicy(sizePolicy)
        self.delta_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.delta_Y.setMaximumSize(QtCore.QSize(120, 20))
        self.delta_Y.setObjectName("delta_Y")
        self.gridLayout_3.addWidget(self.delta_Y, 4, 4, 1, 1)
        self.click1_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click1_Label.sizePolicy().hasHeightForWidth())
        self.click1_Label.setSizePolicy(sizePolicy)
        self.click1_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.click1_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.click1_Label.setObjectName("click1_Label")
        self.gridLayout_3.addWidget(self.click1_Label, 2, 2, 1, 1)
        self.delta_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delta_X.sizePolicy().hasHeightForWidth())
        self.delta_X.setSizePolicy(sizePolicy)
        self.delta_X.setMinimumSize(QtCore.QSize(120, 20))
        self.delta_X.setMaximumSize(QtCore.QSize(120, 20))
        self.delta_X.setObjectName("delta_X")
        self.gridLayout_3.addWidget(self.delta_X, 3, 4, 1, 1)
        self.y_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_Label.sizePolicy().hasHeightForWidth())
        self.y_Label.setSizePolicy(sizePolicy)
        self.y_Label.setMinimumSize(QtCore.QSize(25, 25))
        self.y_Label.setMaximumSize(QtCore.QSize(25, 25))
        self.y_Label.setObjectName("y_Label")
        self.gridLayout_3.addWidget(self.y_Label, 4, 0, 1, 1)
        self.x_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_Label.sizePolicy().hasHeightForWidth())
        self.x_Label.setSizePolicy(sizePolicy)
        self.x_Label.setMinimumSize(QtCore.QSize(25, 25))
        self.x_Label.setMaximumSize(QtCore.QSize(25, 25))
        self.x_Label.setObjectName("x_Label")
        self.gridLayout_3.addWidget(self.x_Label, 3, 0, 1, 1)
        self.click_1_Y = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_1_Y.sizePolicy().hasHeightForWidth())
        self.click_1_Y.setSizePolicy(sizePolicy)
        self.click_1_Y.setMinimumSize(QtCore.QSize(120, 20))
        self.click_1_Y.setMaximumSize(QtCore.QSize(120, 20))
        self.click_1_Y.setObjectName("click_1_Y")
        self.gridLayout_3.addWidget(self.click_1_Y, 4, 2, 1, 1)
        self.current_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_X.sizePolicy().hasHeightForWidth())
        self.current_X.setSizePolicy(sizePolicy)
        self.current_X.setMinimumSize(QtCore.QSize(120, 20))
        self.current_X.setMaximumSize(QtCore.QSize(120, 20))
        self.current_X.setObjectName("current_X")
        self.gridLayout_3.addWidget(self.current_X, 3, 1, 1, 1)
        self.click2_Label = QtWidgets.QLabel(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click2_Label.sizePolicy().hasHeightForWidth())
        self.click2_Label.setSizePolicy(sizePolicy)
        self.click2_Label.setMinimumSize(QtCore.QSize(120, 20))
        self.click2_Label.setMaximumSize(QtCore.QSize(120, 20))
        self.click2_Label.setObjectName("click2_Label")
        self.gridLayout_3.addWidget(self.click2_Label, 2, 3, 1, 1)
        self.click_2_X = QtWidgets.QLineEdit(self.tab_Deltas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_2_X.sizePolicy().hasHeightForWidth())
        self.click_2_X.setSizePolicy(sizePolicy)
        self.click_2_X.setMinimumSize(QtCore.QSize(120, 20))
        self.click_2_X.setMaximumSize(QtCore.QSize(120, 20))
        self.click_2_X.setObjectName("click_2_X")
        self.gridLayout_3.addWidget(self.click_2_X, 3, 3, 1, 1)
        self.button_ClearDeltas = QtWidgets.QPushButton(self.tab_Deltas)
        self.button_ClearDeltas.setObjectName("button_ClearDeltas")
        self.gridLayout_3.addWidget(self.button_ClearDeltas, 1, 3, 1, 1)
        self.option_Deltas = QtWidgets.QCheckBox(self.tab_Deltas)
        self.option_Deltas.setObjectName("option_Deltas")
        self.gridLayout_3.addWidget(self.option_Deltas, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.cursors_Tabber.addTab(self.tab_Deltas, "")
        self.tab_Integrals = QtWidgets.QWidget()
        self.tab_Integrals.setObjectName("tab_Integrals")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_Integrals)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 511, 99))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 1, 1, 1, 1)
        self.integral_Red = QtWidgets.QLineEdit(self.layoutWidget1)
        self.integral_Red.setObjectName("integral_Red")
        self.gridLayout_13.addWidget(self.integral_Red, 2, 0, 1, 1)
        self.integral_Green = QtWidgets.QLineEdit(self.layoutWidget1)
        self.integral_Green.setObjectName("integral_Green")
        self.gridLayout_13.addWidget(self.integral_Green, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 1, 0, 1, 1)
        self.integral_White = QtWidgets.QLineEdit(self.layoutWidget1)
        self.integral_White.setObjectName("integral_White")
        self.gridLayout_13.addWidget(self.integral_White, 2, 3, 1, 1)
        self.integral_Blue = QtWidgets.QLineEdit(self.layoutWidget1)
        self.integral_Blue.setObjectName("integral_Blue")
        self.gridLayout_13.addWidget(self.integral_Blue, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 1, 3, 1, 1)
        self.button_ClearIntegrals = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_ClearIntegrals.setObjectName("button_ClearIntegrals")
        self.gridLayout_13.addWidget(self.button_ClearIntegrals, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_13.addWidget(self.label_6, 0, 0, 1, 1)
        self.integral_Width = QtWidgets.QLineEdit(self.layoutWidget1)
        self.integral_Width.setObjectName("integral_Width")
        self.gridLayout_13.addWidget(self.integral_Width, 0, 1, 1, 1)
        self.cursors_Tabber.addTab(self.tab_Integrals, "")
        self.gridLayout.addWidget(self.cursors_Tabber, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cursors_Tabber.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Controls"))
        self.button_ApplySettings.setText(_translate("MainWindow", "Apply Settings"))
        self.button_Defaults.setText(_translate("MainWindow", "Set to defaults"))
        self.button_StartStop.setText(_translate("MainWindow", "Start/Stop"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Channel Counts"))
        self.counts_Ch0_Label.setText(_translate("MainWindow", "Ch0 (sync)"))
        self.counts_Ch1_Label.setText(_translate("MainWindow", "Ch1 (signal)"))
        self.settings_Box.setTitle(_translate("MainWindow", "Settings"))
        self.histogram_Box.setTitle(_translate("MainWindow", "Histogram"))
        self.button_AutoRange.setText(_translate("MainWindow", "Auto Range"))
        self.filename_Label.setText(_translate("MainWindow", "Save filename:"))
        self.filename.setText(_translate("MainWindow", "histogram.csv"))
        self.button_ClearHistogram.setText(_translate("MainWindow", "Clear Histogram"))
        self.button_SaveHisto.setText(_translate("MainWindow", "Save Histogram"))
        self.option_Cursor.setText(_translate("MainWindow", "Cursor On"))
        self.general_Box.setTitle(_translate("MainWindow", "General"))
        self.resolution_Label.setText(_translate("MainWindow", "Resolution (ps)"))
        self.label_2.setText(_translate("MainWindow", "Acq. Time (ms)"))
        self.ch1_Box.setTitle(_translate("MainWindow", "Ch1 (signal)"))
        self.CFD1_Level_Label.setText(_translate("MainWindow", "Discriminator (mV)"))
        self.CFD1_Zerocross_Label.setText(_translate("MainWindow", "Zero Crossing (mV)"))
        self.ch0_Box.setTitle(_translate("MainWindow", "Ch0 (Sync)"))
        self.CFD0_Zerocross_Label.setText(_translate("MainWindow", "Zero Crossing (mV)"))
        self.CFD0_Level_Label.setText(_translate("MainWindow", "Discriminator (mV)"))
        self.sync_Divider_Label.setText(_translate("MainWindow", "Clock Divider"))
        self.sync_Divider.setItemText(0, _translate("MainWindow", "1"))
        self.sync_Divider.setItemText(1, _translate("MainWindow", "2"))
        self.sync_Divider.setItemText(2, _translate("MainWindow", "4"))
        self.sync_Divider.setItemText(3, _translate("MainWindow", "8"))
        self.sync_Offset_Label.setText(_translate("MainWindow", "Offset (ns)"))
        self.deltas_Label.setText(_translate("MainWindow", "Click1 - Click2"))
        self.current_Label.setText(_translate("MainWindow", "Current (yellow)"))
        self.click1_Label.setText(_translate("MainWindow", "Click1 (red)"))
        self.y_Label.setText(_translate("MainWindow", "Y:"))
        self.x_Label.setText(_translate("MainWindow", "X:"))
        self.click2_Label.setText(_translate("MainWindow", "Click2 (green)"))
        self.button_ClearDeltas.setText(_translate("MainWindow", "Clear Deltas"))
        self.option_Deltas.setText(_translate("MainWindow", "Deltas On?"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Deltas), _translate("MainWindow", "Deltas"))
        self.label_3.setText(_translate("MainWindow", "Green"))
        self.label_4.setText(_translate("MainWindow", "Blue"))
        self.label.setText(_translate("MainWindow", "Red"))
        self.label_5.setText(_translate("MainWindow", "White"))
        self.button_ClearIntegrals.setText(_translate("MainWindow", "Clear Markers"))
        self.label_6.setText(_translate("MainWindow", "Integral Width"))
        self.integral_Width.setText(_translate("MainWindow", "5e-9"))
        self.cursors_Tabber.setTabText(self.cursors_Tabber.indexOf(self.tab_Integrals), _translate("MainWindow", "Integrate"))
from pyqtgraph import PlotWidget
